------------------------------------------------------------------------------------------------
-- CREATE DATA TO TABLE TP_OPERATION_TYPES
------------------------------------------------------------------------------------------------
INSERT INTO TB_OPERATION_TYPES(OPERATIONTYPE_ID, DESCRIPTION) VALUES(1, 'COMPRA A VISTA')
INSERT INTO TB_OPERATION_TYPES(OPERATIONTYPE_ID, DESCRIPTION) VALUES(2, 'COMPRA PARCELADA')
INSERT INTO TB_OPERATION_TYPES(OPERATIONTYPE_ID, DESCRIPTION) VALUES(3, 'SAQUE')
INSERT INTO TB_OPERATION_TYPES(OPERATIONTYPE_ID, DESCRIPTION) VALUES(4, 'PAGAMENTO')